apiVersion: v1
kind: Service
metadata:
  namespace: common
  name: minio

spec:
  type: ClusterIP
  selector:
    app: minio-label-srv
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000